# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idanswer', models.IntegerField(primary_key=True, serialize=False)),
                ('idquiz', models.IntegerField(blank=True, null=True)),
                ('ans', models.CharField(blank=True, max_length=45, null=True)),
                ('yans', models.CharField(blank=True, db_column='yAns', max_length=45, null=True)),
            ],
            options={
                'db_table': 'answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quetion',
            fields=[
                ('idquetion', models.IntegerField(primary_key=True, serialize=False)),
                ('idquiz', models.IntegerField()),
                ('q_d', models.CharField(max_length=45)),
                ('a', models.CharField(blank=True, db_column='A', max_length=45, null=True)),
                ('b', models.CharField(blank=True, db_column='B', max_length=45, null=True)),
                ('c', models.CharField(blank=True, db_column='C', max_length=45, null=True)),
                ('d', models.CharField(blank=True, db_column='D', max_length=45, null=True)),
                ('ans', models.CharField(blank=True, db_column='Ans', max_length=45, null=True)),
                ('marks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'quetion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quizdetails',
            fields=[
                ('idquiz', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=45)),
                ('timelimit', models.IntegerField(blank=True, db_column='timeLimit', null=True)),
                ('subject', models.CharField(blank=True, max_length=45, null=True)),
                ('total', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('time', models.CharField(blank=True, db_column='Time', max_length=45, null=True)),
            ],
            options={
                'db_table': 'quizDetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=45)),
                ('type', models.CharField(db_column='Type', max_length=45)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Userrecord',
            fields=[
                ('iduserrecord', models.IntegerField(db_column='iduserRecord', primary_key=True, serialize=False)),
                ('idquiz', models.IntegerField(blank=True, null=True)),
                ('iduser', models.IntegerField(blank=True, db_column='idUser', null=True)),
                ('score', models.IntegerField(blank=True, db_column='Score', null=True)),
                ('userrecordcol', models.CharField(blank=True, db_column='userRecordcol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'userRecord',
                'managed': True,
            },
        ),
    ]
