# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Quetion',
        ),
        migrations.DeleteModel(
            name='Quizdetails',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Userrecord',
        ),
    ]
